<%@ Page Title="" Language="C#" MasterPageFile="~/SWCharactersmp.Master" AutoEventWireup="true" CodeBehind="BabyYoda.aspx.cs" Inherits="StarWarsCharactersmp.BabyYoda" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
            <h2 style="text-align: center; text-decoration: underline; ">Baby Yoda:</h2>
            Grogu was a male Force-sensitive Mandalorian belonging to the same mysterious species as the legendary Grand Master Yoda. Grogu was born in the year 41 BBY, and was raised at the Jedi Temple on Coruscant as a Jedi Initiate of the Jedi Order. Grogu survived the Great Jedi Purge and was hidden away. Grogu was rediscovered by a remnant of the Galactic Empire after it fell, and became known to many simply as "The Child," during the New Republic Era. However Grogu was rescued by Din Djarin, a Mandalorian bounty hunter where he became a foundling. Djarin was able to find a Jedi to train him and he rejoined the Jedi Order under Jedi Master Luke Skywalker. However, Skywalker sensed that Grogu's heart was not in learning the Jedi path, thus he subsequently gave in to his attachment to the Mandalorian.

            Grogu was born in the year 41 BBY, and was raised at the Jedi Temple on Coruscant as a Jedi Initiate of the Jedi Order and taken into hiding after the Galactic Empire was formed. Eventually, he was held at a hideout run by Nikto mercenaries on Arvala-7 during the era of the New Republic, having survived the siege of the Jedi Temple decades prior. While still an infant at the age of fifty years, he was sought by the "the Client", on behalf of Moff Gideon and Doctor Pershing, by an Imperial client who hired Djarin to retrieve him.

            However, Djarin chose not to leave Grogu with the remnant and rescued him from the Imperial Remnant safe house. After attempting to hide with Grogu along the fringes of the galaxy, Djarin returned to Nevarro to deal with the Imperials chasing Grogu in hopes of keeping him safe. In the process, Grogu became a Mandalorian foundling and the single other member of Djarin's newly created clan. As a result, Djarin took up a quest to deliver Grogu back to the Jedi. Djarin, alongside Grogu, would then travel across the galaxy, searching for the few remaining Jedi who were left. As advised by former Jedi Ahsoka Tano, Djarin would eventually travel with Grogu to Tython, where he could reach out through the Force to find another member of his kind. However, Grogu was captured by Imperial forces, and Djarin was forced to lead a mission to rescue him. After being reunited with Grogu, Djarin delivered him to Luke Skywalker, a Jedi who agreed to take the child into his care and train him in the ways of the Force.

            Grogu renewed his training under Skywalker and spent a relatively short period of time training with Skywalker on Ossus, where Skywalker was building a Jedi Academy. However, Skywalker sensed that the child's heart was not in learning the Jedi path. After Djarin visited the planet bearing a gift of chain mail armor for Grogu, Skywalker presented the child with a choice: accepting the gift and returning to the Mandalorian, or taking Yoda's lightsaber and continue with his Jedi training. Grogu chose to return to Djarin, and was reunited with him on Tatooine in the middle of a gang war between Boba Fett's forces, whom Djarin was aiding, and the Pyke Syndicate.            <br />
            <div style="text-align: center;">
                <img src= "Images/BabyYoda1.jpg" width="400" height="300" />
                <img src= "Images/BabyYoda2.jpg" width="400" height="300" />
                <img src= "Images/BabyYoda3.jpg" width="400" height="300" />
            </div>
</asp:Content>
