<%@ Page Title="" Language="C#" MasterPageFile="~/SWCharactersmp.Master" AutoEventWireup="true" CodeBehind="DarthVader.aspx.cs" Inherits="StarWarsCharactersmp.DarthVader" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
            <h2 style="text-align: center; text-decoration: underline; ">Darth Vader:</h2>
            Anakin Skywalker was a Force-sensitive Human male who served the Galactic Republic as a Jedi Knight and later served the Galactic Empire as the Sith Lord Darth Vader. Born to the slave Shmi Skywalker in 41.9 BBY, Anakin was conceived by midi-chlorians, the symbiotic organisms that allowed individuals to touch the Force, and he and his mother were brought to the desert planet of Tatooine to be the slaves of Gardulla the Hutt. They soon ended up as the property of the Toydarian Watto, and Skywalker exhibited exceptional piloting skills and a reputation for being able to build and repair anything even at a young age. In 32 BBY, Skywalker encountered the Jedi Qui-Gon Jinn and Padmé Amidala, and he helped them secure the parts they needed for their starship by winning the Boonta Eve Classic podracing event—only to learn that he had also won his freedom in doing so.

            Reluctantly leaving his mother behind, Skywalker accompanied Jinn and his group to the Republic's capital of Coruscant and participated in the Battle of Naboo, helping to free Amidala's homeworld from the armies of the Trade Federation. While Jinn was killed during the battle, Jinn's student Obi-Wan Kenobi followed Jinn's wishes and took on Skywalker as his Padawan, and much of the Jedi Council believed that Skywalker was the Chosen One of Jedi prophecy: one who would bring balance to the Force by destroying the Sith Order. Skywalker and Kenobi had a number of adventures during the Padawan's decade of training to become a Jedi, but as the Separatist Crisis threatened to tear the Republic apart in 22 BBY, Skywalker was reunited with Amidala when he was assigned to protect her from assassins. The two grew close during the course of the assignment, though they were caught up in the Battle of Geonosis and the beginning of the Clone Wars between the Republic and the Confederacy of Independent Systems. Losing an arm during the fighting, Skywalker received a cybernetic replacement, and he and Amidala were secretly married in the days after the battle, despite the Jedi Code's restrictions on romantic attachments.

            During the Clone Wars, which raged for the next three years, Skywalker was granted the rank of Jedi Knight and became known to the public as the "Hero with No Fear." Taking on the Togruta Ahsoka Tano as his apprentice, Skywalker fought alongside Kenobi and his fellow Jedi in scores of battles, and his friendship with Supreme Chancellor Palpatine deepened despite the Jedi Order's wariness of Palpatine's rapid acquisition of further powers during the course of the war. Throughout the Clone Wars, Skywalker's anger and sense of loss pushed him ever closer to the dark side of the Force, and his visions of Amidala dying in childbirth in 19 BBY made him desperate to find a way to save his wife. Palpatine, who was actually the Sith Lord Darth Sidious, seduced Skywalker into becoming his apprentice with the promise of saving Amidala, and Skywalker was christened Darth Vader as Palpatine transformed the Republic into the Galactic Empire and eradicated the Jedi Order.

            Vader and Kenobi clashed on Mustafar after Vader attacked his wife in the belief that she had betrayed him, and the newly christened Sith Lord was left limbless and ravaged by fire at the end of their battle. Encased in a suit of life-sustaining black armor and believing his wife to be dead, Vader embraced his role as the Emperor's right hand, hunting down Jedi survivors, crushing Separatist holdouts and ensuring the fulfillment of "his" Empire's policies for years to come, actions that awarded him special powers and ultimately the position of Supreme Commander of Imperial Forces. The Sith Lord trained a number of secret apprentices and other Dark Jedi disciples, though his plans to overthrow his master had not advanced far when the Galactic Civil War erupted between the Empire and the Alliance to Restore the Republic in 2 BBY. In 0 BBY, the Death Star—the Empire's greatest superweapon—was destroyed by a young Rebel pilot despite Vader's efforts, and the Sith Lord became obsessed with discovering the pilot's identity, only to learn that it was Luke Skywalker: his own son, born before Amidala's death.

            Vader continued to pursue both Skywalker and the Alliance over the next three years, finally luring his son into a trap on the mining colony of Cloud City in 3 ABY where the two dueled. Vader revealed his identity to Skywalker, though his son refused to join him and escaped. When Darth Sidious learned of Skywalker's existence, he set in motion his own plans to recruit Skywalker and thereby replace Vader, but Skywalker surrendered himself to Imperial forces on the forest moon of Endor in 4 ABY in hopes of redeeming his father and turning him back to the light side. In a final duel on the second Death Star as the Battle of Endor raged around them, Skywalker and Vader fought each other, and Vader refused his son's attempts to redeem him, learning that Skywalker had a twin sister named Leia in the process. Skywalker defeated his father but refused to kill him, and when Sidious attempted to kill the young man, Vader—moved by his son's love—abandoned the dark side and sacrificed himself to destroy the Emperor, fulfilling the prophecy of the Chosen One. Mortally wounded, Anakin made peace with his son and became one with the Force, though his reputation, his legacy, and his family endured for decades afterwards.            <br />
            <div style="text-align: center;">
                <img src="Images/DarthVader1.png" width="400" height="300" />
                <img src="Images/DarthVader2.jpg" width="400" height="300" />
                <img src="Images/DarthVader3.jpg" width="400" height="300" />
            </div>
</asp:Content>
