<%@ Page Title="" Language="C#" MasterPageFile="~/SWCharactersmp.Master" AutoEventWireup="true" CodeBehind="Palpatine.aspx.cs" Inherits="StarWarsCharactersmp.Palpatine" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <h2 style="text-align: center; text-decoration: underline; ">Palptine (Darth Sidious):</h2>
        <br />
            Darth Sidious, born Sheev Palpatine and also known simply as the Emperor, was a human male Dark Lord of the Sith and Emperor of the Galactic Empire, ruling from 19 BBY to 4 ABY. Rising to power in the Galactic Senate as the senator of Naboo, the secretive Sith Lord cultivated two identities, Sidious and Palpatine, using both to further his political career and deceive his way into accomplishing his goal. He orchestrated the fall of the Galactic Republic and the Jedi Order through the Clone Wars, and then established his reign over the galaxy which lasted until his death at the Battle of Endor. However, the dark side of the Force gave rise to powers which allowed the Emperor to return from the grave.

            Born on the Mid Rim planet Naboo in 82 BBY during the Republic Era, Sidious possessed a strong connection to the Force, and was secretly trained in the ways of the Sith by Darth Plagueis. He eventually betrayed and killed his Sith Master, in order to train his own Sith apprentice, Darth Maul, for the Rule of Two limited their ranks to two Sith Lords at any given time. As a result of the Invasion of Naboo, a crisis orchestrated by Sidious, the Senate elected Palpatine as Supreme Chancellor. The Separatist Crisis and the Clone Wars were masterminded by Sidious and his new apprentice, Darth Tyranus, in an effort to achieve galactic dominance. Following an attempt to arrest the chancellor, the Great Jedi Purge commenced with Sidious enacting Order 66.

            With the Jedi all but extinct, Sidious installed the New Order in the Republic's place, declaring himself Galactic Emperor and bringing an end to millenia of democracy. Not too long after betraying and causing the death of Tyranus, he took on a new apprentice, having lured the Jedi Knight Anakin Skywalker to the dark side and transforming him into Darth Vader. Their reign was virtually unchallenged for a generation until the formation of the Alliance to Restore the Republic. During the Galactic Civil War, the Emperor sought to betray Vader, by replacing him with the latter's son, Luke Skywalker. However, Sidious' plan backfired when Vader ultimately renounced the dark side and killed Sidious to protect Luke. Thus, with the Sith's destruction, the Force was brought back into balance, fulfilling Anakin's destiny as the prophesied Chosen One.

            Through his master's teachings, however, Sidious transferred his essence to an imperfect clone vessel that had been modeled on his original body. Anticipating the possibility of defeat, he created the Contingency to destroy the Galactic Empire and replace it with a new Sith Empire, in the event of such a setback. His plans culminated in the destruction of the New Republic and the emergence of the First Order, the creation of Supreme Leader Snoke, who turned Ben Solo—heir to the Skywalker bloodline—to the dark side, and the establishment of the Final Order. When the Emperor announced his return to the galaxy in 35 ABY, the Resistance invaded the planet Exegol, Sidious' hidden stronghold in the Unknown Regions. During the battle, he discovered a dyad in the Force in the form of the bond between Solo and Rey, a Jedi apprentice sired from the Emperor's bloodline. His lifelong dream of eternal rule was finally quashed when Rey called upon the strength of past Jedi to vanquish her grandfather by turning his own power against him, destroying Sidious and his Sith Eternal cultists.
            <br />
            <div style="text-align: center;">
                <img src="Images/Palpatine1.jpg" width="400" height="300" />
                <img src="Images/Palpatine2.png" width="400" height="300" />
                <img src="Images/Palpatine3.jpg" width="400" height="300" />
            </div>
</asp:Content>
